# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.map_scanner.root] run return 0
execute on passengers if entity @s[tag=aj.map_scanner.data] unless data entity @s {data:{rigHash: '461ad7b98957713bf1853fa6f7ec482a97b25860a2ceefd18387bc210ef230ca'}} on vehicle run function animated_java:map_scanner/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1