# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.cccube.root] run return 0
execute on passengers if entity @s[tag=aj.cccube.data] unless data entity @s {data:{rigHash: 'd19ff597caedfaebf44d34eaf6a5c39679e488b2520449032c75c6aadc57a4cc'}} on vehicle run function animated_java:cccube/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1