# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.cccube.root] run return 0
execute on passengers if entity @s[tag=aj.cccube.data] unless data entity @s {data:{rigHash: '6cc7dc52ba2ca1ec5e299b7da8d78b050e2d9ab4822f1d682fb6b2355ae3ae25'}} on vehicle run function animated_java:cccube/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1