# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.cccube.root] run return 0
execute on passengers if entity @s[tag=aj.cccube.data] unless data entity @s {data:{rigHash: '6bb5bda43d1c1ae53ca2a01e7ef3dfea0dfb09a5a02f47aed64065e90c15e218'}} on vehicle run function animated_java:cccube/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1