# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.cccube_inspector_opening.frame dummy
scoreboard objectives add aj.cccube_front_sliders_open.frame dummy
scoreboard objectives add aj.cccube_slider1_on.frame dummy
scoreboard objectives add aj.cccube_slider2_on.frame dummy
scoreboard objectives add aj.cccube_color_puzzle_open.frame dummy
scoreboard objectives add aj.cccube_mirror_shelf_open.frame dummy
scoreboard objectives add aj.laser_catcher_open.frame dummy
scoreboard objectives add aj.code_lock_open.frame dummy
scoreboard objectives add aj.mys_cube_open.frame dummy
scoreboard objectives add aj.acs_open.frame dummy