# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.lasergun.root] run return 0
execute on passengers if entity @s[tag=aj.lasergun.data] unless data entity @s {data:{rigHash: '8c3419301176bab6d4a5d0e72d1df3b8b0c9d58cc468e5f7c56a88ef32885b30'}} on vehicle run function animated_java:lasergun/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1