# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.lasergun.root] run return 0
execute on passengers if entity @s[tag=aj.lasergun.data] unless data entity @s {data:{rigHash: 'c3b1309f548e1dac31ca9626b8c9da65a8b80a2f0b934434e415557bce3ea26b'}} on vehicle run function animated_java:lasergun/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1