# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.mirror_open.frame dummy
scoreboard objectives add aj.mirror_close.frame dummy
scoreboard objectives add aj.mirror_open_flipped.frame dummy
scoreboard objectives add aj.mirror_close_flipped.frame dummy
scoreboard objectives add aj.mirror_open_left.frame dummy
scoreboard objectives add aj.mirror_close_left.frame dummy
scoreboard objectives add aj.mirror_open_flipped_right.frame dummy
scoreboard objectives add aj.mirror_close_flipped_right.frame dummy
scoreboard objectives add aj.mirror_open_side_right.frame dummy
scoreboard objectives add aj.mirror_close_side_right.frame dummy