# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lasergun.node.ring3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ring3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lasergun.node.ring1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ring1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lasergun.node.ring2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ring2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lasergun.node.tip2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tip2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lasergun.node.tip1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tip1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lasergun.node.gun] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_gun set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lasergun.node.rot] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rot set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lasergun.node.ext2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ext2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lasergun.node.extender] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_extender set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lasergun.node.lasergun] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_lasergun set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lasergun.node.lid] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_lid set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lasergun.node.box] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_box set from storage aj:uuid main.out