# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.lasergun_open.frame dummy
scoreboard objectives add aj.lasergun_loop.frame dummy
scoreboard objectives add aj.lasergun_close.frame dummy