# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.mindmap.root] run return 0
execute on passengers if entity @s[tag=aj.mindmap.data] unless data entity @s {data:{rigHash: '1ae3a20c4dfc7708f19d9f14b1fa402bc4d7f6bbbd380253d8319684684fe34c'}} on vehicle run function animated_java:mindmap/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1