# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.mindmap.root] run return 0
execute on passengers if entity @s[tag=aj.mindmap.data] unless data entity @s {data:{rigHash: '4ba543d03c8ae2dc653d90ab99300cdcf98509dc29498947be608c26be360742'}} on vehicle run function animated_java:mindmap/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1