# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.mindmap.root] run return 0
execute on passengers if entity @s[tag=aj.mindmap.data] unless data entity @s {data:{rigHash: 'e62be6903bd9b658c6b59c8226c9125f5d14ebf67ae7b1811c844baa24adb1a3'}} on vehicle run function animated_java:mindmap/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1