# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.elevator.root] run return 0
execute on passengers if entity @s[tag=aj.elevator.data] unless data entity @s {data:{rigHash: 'dab270d68055a7c89f956e405ea23d3dc6afb6f5a98a5e2829a4d39d2cc8d0dc'}} on vehicle run function animated_java:elevator/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1