# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.cccube.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'cccube', 'function_path': 'animated_java:cccube/animations/pause_all'}
tag @s remove aj.cccube.animation.cccube_inspector_opening.playing
tag @s remove aj.cccube.animation.cccube_front_sliders_open.playing
tag @s remove aj.cccube.animation.cccube_slider1_on.playing
tag @s remove aj.cccube.animation.cccube_slider2_on.playing
tag @s remove aj.cccube.animation.cccube_color_puzzle_open.playing
tag @s remove aj.cccube.animation.cccube_mirror_shelf_open.playing
tag @s remove aj.cccube.animation.laser_catcher_open.playing
tag @s remove aj.cccube.animation.code_lock_open.playing
tag @s remove aj.cccube.animation.mys_cube_open.playing
tag @s remove aj.cccube.animation.acs_open.playing