# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.mindmap.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'mindmap', 'function_path': 'animated_java:mindmap/animations/mindmap_text/next_frame'}
execute if score @s aj.mindmap_text.frame matches 2.. run scoreboard players set @s aj.mindmap_text.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.mindmap_text.frame
execute at @s run function animated_java:mindmap/animations/mindmap_text/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.mindmap_text.frame 1