# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.map_scanner.node.scan1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_scan1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.map_scanner.node.scan2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_scan2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.map_scanner.node.success] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_success set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.map_scanner.node.fail] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_fail set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.map_scanner.node.top] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_top set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.map_scanner.node.map_scanner] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_map_scanner set from storage aj:uuid main.out