# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mindmap.node.frame] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_frame set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mindmap.node.board] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_board set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mindmap.node.bone] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mindmap.node.bone3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mindmap.node.bone1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mindmap.node.bone9] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone9 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mindmap.node.bone10] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone10 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mindmap.node.bone11] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone11 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mindmap.node.bone2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mindmap.node.bone4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mindmap.node.papers] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_papers set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mindmap.node.pins] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_pins set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mindmap.node.bone8] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone8 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mindmap.node.bone6] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mindmap.node.bone7] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone7 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mindmap.node.bone5] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mindmap.node.conduit] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_conduit set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mindmap.node.acs] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_acs set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mindmap.node.life_essence] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_life_essence set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mindmap.node.ac] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ac set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mindmap.node.illusioner] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_illusioner set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mindmap.node.beacon] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_beacon set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mindmap.node.cybermagic] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.text_display_cybermagic set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mindmap.node.question] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.text_display_question set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mindmap.node.another] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.text_display_another set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mindmap.node.dangerous] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.text_display_dangerous set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mindmap.node.applicable] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.text_display_applicable set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mindmap.node.controls] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.text_display_controls set from storage aj:uuid main.out