# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:stable_mirror/root/zzz/2 with entity @s data.locators.1
function animated_java:stable_mirror/root/zzz/4 with entity @s data.locators.2
function animated_java:stable_mirror/root/zzz/6 with entity @s data.locators.button