# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.cccube.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'cccube', 'function_path': 'animated_java:cccube/animations/cccube_inspector_opening/next_frame'}
execute if score @s aj.cccube_inspector_opening.frame matches 161.. run scoreboard players set @s aj.cccube_inspector_opening.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.cccube_inspector_opening.frame
execute at @s run function animated_java:cccube/animations/cccube_inspector_opening/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.cccube_inspector_opening.frame 1