# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:temp uuid set from entity @s data.locators.1.uuid
function animated_java:stable_mirror/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.2.uuid
function animated_java:stable_mirror/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.button.uuid
function animated_java:stable_mirror/zzz/execute with storage aj:temp