# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.map_scanner_scan.frame dummy
scoreboard objectives add aj.map_scanner_success.frame dummy
scoreboard objectives add aj.map_scanner_fail.frame dummy