# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.lasergun.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'lasergun', 'function_path': 'animated_java:lasergun/animations/lasergun_loop/stop'}
tag @s remove aj.lasergun.animation.lasergun_loop.playing
scoreboard players set @s aj.lasergun_loop.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:lasergun/animations/lasergun_loop/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only