# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:cccube/remove/zzz/kill with entity @s data.locators.keycard_slot_interact
function animated_java:cccube/remove/zzz/kill with entity @s data.locators.spyglass
function animated_java:cccube/remove/zzz/kill with entity @s data.locators.inspector_platform