# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.elevator.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'elevator', 'function_path': 'animated_java:elevator/animations/elevator_prepare/next_frame'}
execute if score @s aj.elevator_prepare.frame matches 46.. run scoreboard players set @s aj.elevator_prepare.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.elevator_prepare.frame
execute at @s run function animated_java:elevator/animations/elevator_prepare/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.elevator_prepare.frame 1