# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.stable_mirror.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'stable_mirror', 'function_path': 'animated_java:stable_mirror/animations/pause_all'}
tag @s remove aj.stable_mirror.animation.mirror_open.playing
tag @s remove aj.stable_mirror.animation.mirror_close.playing
tag @s remove aj.stable_mirror.animation.mirror_open_flipped.playing
tag @s remove aj.stable_mirror.animation.mirror_close_flipped.playing
tag @s remove aj.stable_mirror.animation.mirror_open_left.playing
tag @s remove aj.stable_mirror.animation.mirror_close_left.playing
tag @s remove aj.stable_mirror.animation.mirror_open_flipped_right.playing
tag @s remove aj.stable_mirror.animation.mirror_close_flipped_right.playing
tag @s remove aj.stable_mirror.animation.mirror_open_side_right.playing
tag @s remove aj.stable_mirror.animation.mirror_close_side_right.playing