# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.stable_mirror.root] run return 0
execute on passengers if entity @s[tag=aj.stable_mirror.data] unless data entity @s {data:{rigHash: '334c146aa20bfda3e10650939fe4ab48c8486f3bb858d7f634523e782041ee53'}} on vehicle run function animated_java:stable_mirror/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1