# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.unanimated] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_unanimated set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.inspector_base] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_inspector_base set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.inspector_interior] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_inspector_interior set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.keycard] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_keycard set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.lev_orb] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_lev_orb set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.platform] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_platform set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.mechrot] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_mechrot set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.mech] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_mech set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.initial_mech] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_initial_mech set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.platform_support] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_platform_support set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.sp1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_sp1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.sp2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_sp2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.sp3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_sp3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.sp_mech] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_sp_mech set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.spyglass_platform] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_spyglass_platform set from storage aj:uuid main.out