# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
summon minecraft:interaction ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.cccube.locator', 'aj.cccube.locator']}
execute as @e[type=minecraft:interaction,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:cccube/zzz/2
data modify entity @s data.locators.keycard_slot_interact.uuid set from storage aj:uuid main.out
summon minecraft:marker ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.cccube.locator', 'aj.cccube.locator']}
execute as @e[type=minecraft:marker,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:cccube/zzz/3
data modify entity @s data.locators.spyglass.uuid set from storage aj:uuid main.out
summon minecraft:marker ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.cccube.locator', 'aj.cccube.locator']}
execute as @e[type=minecraft:marker,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:cccube/zzz/4
data modify entity @s data.locators.inspector_platform.uuid set from storage aj:uuid main.out
summon minecraft:interaction ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.cccube.locator', 'aj.cccube.locator']}
execute as @e[type=minecraft:interaction,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:cccube/zzz/5
data modify entity @s data.locators.slider1.uuid set from storage aj:uuid main.out
summon minecraft:interaction ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.cccube.locator', 'aj.cccube.locator']}
execute as @e[type=minecraft:interaction,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:cccube/zzz/6
data modify entity @s data.locators.slider2.uuid set from storage aj:uuid main.out
summon minecraft:interaction ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.cccube.locator', 'aj.cccube.locator']}
execute as @e[type=minecraft:interaction,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:cccube/zzz/7
data modify entity @s data.locators.mys_cube_interaction.uuid set from storage aj:uuid main.out
summon minecraft:interaction ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.cccube.locator', 'aj.cccube.locator']}
execute as @e[type=minecraft:interaction,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:cccube/zzz/8
data modify entity @s data.locators.cpi_black.uuid set from storage aj:uuid main.out
summon minecraft:interaction ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.cccube.locator', 'aj.cccube.locator']}
execute as @e[type=minecraft:interaction,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:cccube/zzz/9
data modify entity @s data.locators.cpi_blue.uuid set from storage aj:uuid main.out
summon minecraft:interaction ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.cccube.locator', 'aj.cccube.locator']}
execute as @e[type=minecraft:interaction,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:cccube/zzz/10
data modify entity @s data.locators.cpi_cyan.uuid set from storage aj:uuid main.out
summon minecraft:interaction ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.cccube.locator', 'aj.cccube.locator']}
execute as @e[type=minecraft:interaction,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:cccube/zzz/11
data modify entity @s data.locators.cpi_green.uuid set from storage aj:uuid main.out
summon minecraft:interaction ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.cccube.locator', 'aj.cccube.locator']}
execute as @e[type=minecraft:interaction,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:cccube/zzz/12
data modify entity @s data.locators.cpi_orange.uuid set from storage aj:uuid main.out
summon minecraft:interaction ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.cccube.locator', 'aj.cccube.locator']}
execute as @e[type=minecraft:interaction,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:cccube/zzz/13
data modify entity @s data.locators.cpi_pink.uuid set from storage aj:uuid main.out
summon minecraft:interaction ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.cccube.locator', 'aj.cccube.locator']}
execute as @e[type=minecraft:interaction,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:cccube/zzz/14
data modify entity @s data.locators.cpi_purple.uuid set from storage aj:uuid main.out
summon minecraft:interaction ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.cccube.locator', 'aj.cccube.locator']}
execute as @e[type=minecraft:interaction,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:cccube/zzz/15
data modify entity @s data.locators.cpi_red.uuid set from storage aj:uuid main.out
summon minecraft:interaction ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.cccube.locator', 'aj.cccube.locator']}
execute as @e[type=minecraft:interaction,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:cccube/zzz/16
data modify entity @s data.locators.cpi_white.uuid set from storage aj:uuid main.out
summon minecraft:interaction ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.cccube.locator', 'aj.cccube.locator']}
execute as @e[type=minecraft:interaction,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:cccube/zzz/17
data modify entity @s data.locators.cpi_yellow.uuid set from storage aj:uuid main.out
summon minecraft:interaction ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.cccube.locator', 'aj.cccube.locator']}
execute as @e[type=minecraft:interaction,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:cccube/zzz/18
data modify entity @s data.locators.mirror_interaction.uuid set from storage aj:uuid main.out
summon minecraft:marker ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.cccube.locator', 'aj.cccube.locator']}
execute as @e[type=minecraft:marker,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:cccube/zzz/19
data modify entity @s data.locators.laser_catcher_marker.uuid set from storage aj:uuid main.out
summon minecraft:interaction ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.cccube.locator', 'aj.cccube.locator']}
execute as @e[type=minecraft:interaction,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:cccube/zzz/20
data modify entity @s data.locators.cd_1.uuid set from storage aj:uuid main.out
summon minecraft:marker ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.cccube.locator', 'aj.cccube.locator']}
execute as @e[type=minecraft:marker,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:cccube/zzz/21
data modify entity @s data.locators.screen.uuid set from storage aj:uuid main.out
summon minecraft:interaction ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.cccube.locator', 'aj.cccube.locator']}
execute as @e[type=minecraft:interaction,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:cccube/zzz/22
data modify entity @s data.locators.cd_2.uuid set from storage aj:uuid main.out
summon minecraft:interaction ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.cccube.locator', 'aj.cccube.locator']}
execute as @e[type=minecraft:interaction,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:cccube/zzz/23
data modify entity @s data.locators.cd_3.uuid set from storage aj:uuid main.out
summon minecraft:interaction ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.cccube.locator', 'aj.cccube.locator']}
execute as @e[type=minecraft:interaction,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:cccube/zzz/24
data modify entity @s data.locators.cd_4.uuid set from storage aj:uuid main.out
summon minecraft:interaction ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.cccube.locator', 'aj.cccube.locator']}
execute as @e[type=minecraft:interaction,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:cccube/zzz/25
data modify entity @s data.locators.cd_5.uuid set from storage aj:uuid main.out
summon minecraft:interaction ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.cccube.locator', 'aj.cccube.locator']}
execute as @e[type=minecraft:interaction,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:cccube/zzz/26
data modify entity @s data.locators.cd_6.uuid set from storage aj:uuid main.out
summon minecraft:interaction ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.cccube.locator', 'aj.cccube.locator']}
execute as @e[type=minecraft:interaction,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:cccube/zzz/27
data modify entity @s data.locators.cd_7.uuid set from storage aj:uuid main.out
summon minecraft:interaction ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.cccube.locator', 'aj.cccube.locator']}
execute as @e[type=minecraft:interaction,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:cccube/zzz/28
data modify entity @s data.locators.cd_8.uuid set from storage aj:uuid main.out
summon minecraft:interaction ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.cccube.locator', 'aj.cccube.locator']}
execute as @e[type=minecraft:interaction,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:cccube/zzz/29
data modify entity @s data.locators.cd_9.uuid set from storage aj:uuid main.out
summon minecraft:item_display ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.cccube.locator', 'aj.cccube.locator']}
execute as @e[type=minecraft:item_display,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:cccube/zzz/30
data modify entity @s data.locators.acs_item.uuid set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.keycard_slot] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_keycard_slot set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.unanimated] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_unanimated set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.inspector_base] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_inspector_base set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.inspector_interior] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_inspector_interior set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.keycard] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_keycard set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.base] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_base set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.lev_orb] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_lev_orb set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.mechrot] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_mechrot set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.mech] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_mech set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.initial_mech] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_initial_mech set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.platform_support] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_platform_support set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.sp1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_sp1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.sp2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_sp2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.sp3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_sp3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.sp_mech] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_sp_mech set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.spyglass_platform] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_spyglass_platform set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.front_sliders_doors] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_front_sliders_doors set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.slider_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_slider_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.slider_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_slider_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.front_sliders] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_front_sliders set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.door1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_door1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.door2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_door2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.walls] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_walls set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.cpc_black] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_cpc_black set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.cpc_blue] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_cpc_blue set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.cpc_cyan] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_cpc_cyan set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.cpc_green] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_cpc_green set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.cpc_orange] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_cpc_orange set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.cpc_pink] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_cpc_pink set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.cpc_purple] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_cpc_purple set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.cpc_red] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_cpc_red set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.cpc_white] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_cpc_white set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.cpc_yellow] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_cpc_yellow set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.mirror1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_mirror1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.mirror2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_mirror2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.mirror_shelf] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_mirror_shelf set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.interior] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_interior set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.ls_door] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ls_door set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.catchers] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_catchers set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.catcher] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_catcher set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.cd_door] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_cd_door set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.cd_door2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_cd_door2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.the_lock] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_the_lock set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.cd_interior] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_cd_interior set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.mys_cube_item] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_mys_cube_item set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.mcs_interior] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_mcs_interior set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.acs_interior] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_acs_interior set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.rail_extender] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rail_extender set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.rails] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rails set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.acs_support] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_acs_support set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.acs_base] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_acs_base set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.acs_door2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_acs_door2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.cccube.node.acs_door1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_acs_door1 set from storage aj:uuid main.out