# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:temp uuid set from entity @s data.locators.keycard_slot_interact.uuid
function animated_java:cccube/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.spyglass.uuid
function animated_java:cccube/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.inspector_platform.uuid
function animated_java:cccube/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.slider1.uuid
function animated_java:cccube/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.slider2.uuid
function animated_java:cccube/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.cpi_black.uuid
function animated_java:cccube/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.cpi_blue.uuid
function animated_java:cccube/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.cpi_cyan.uuid
function animated_java:cccube/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.cpi_green.uuid
function animated_java:cccube/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.cpi_orange.uuid
function animated_java:cccube/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.cpi_pink.uuid
function animated_java:cccube/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.cpi_purple.uuid
function animated_java:cccube/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.cpi_red.uuid
function animated_java:cccube/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.cpi_white.uuid
function animated_java:cccube/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.cpi_yellow.uuid
function animated_java:cccube/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.mirror_interaction.uuid
function animated_java:cccube/zzz/execute with storage aj:temp