# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.new
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
tag @s add ccww.cpi.black
tag @s add ccww.cpi
data merge entity @s {width:0.3125,height:0.3125}