# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.map_scanner.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'map_scanner', 'function_path': 'animated_java:map_scanner/animations/pause_all'}
tag @s remove aj.map_scanner.animation.map_scanner_fail.playing
tag @s remove aj.map_scanner.animation.map_scanner_scan.playing
tag @s remove aj.map_scanner.animation.map_scanner_success.playing