# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.cccube.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'cccube', 'function_path': 'animated_java:cccube/animations/cccube_slider1_on/play'}
tag @s add aj.cccube.animation.cccube_slider1_on.playing
scoreboard players set @s aj.cccube_slider1_on.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:cccube/animations/cccube_slider1_on/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only